export const ACTION_TYPES = {
REGISTER_LOADING : 'REGISTER_LOADING',
REGISTER_SUCCESS : 'REGISTER_SUCCESS',
REGISTER_FAIL :'REGISTER_FAIL',
LOGIN_SUCCESS : 'LOGIN_SUCCESS',
LOGIN_FAIL : 'LOGIN_FAIL',
LOGIN_LOADING : 'LOGIN_LOADING',
CLEAR_AUTH_STATE : 'CLEAR_AUTH_STATE',
LOGOUT_USER : 'LOGOUT_USER',
CLEAR_AUTH_STATE : 'CLEAR_AUTH_STATE'
}